# PlatformIO pre-script: derives the firmware version from git and writes it
# to a generated header (only rewritten when it changes, so only the few
# files that include it rebuild - a -D flag would rebuild everything).
#
#   tagged commit v0.1.0        -> 0.1.0
#   any other commit            -> 0.1.0-dev+<hash>[.dirty]   (base from ../VERSION)
#   SM_VERSION env var (CI)     -> used as-is
import os
import subprocess

Import("env")  # noqa: F821

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
repo_dir = os.path.dirname(project_dir)


def git(*args):
    try:
        return subprocess.check_output(["git", *args], cwd=repo_dir, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""


with open(os.path.join(repo_dir, "VERSION")) as f:
    base = f.read().strip()

commit = git("rev-parse", "--short=8", "HEAD") or "unknown"
dirty = bool(git("status", "--porcelain", "--untracked-files=no"))
tag = git("describe", "--tags", "--exact-match", "--match", "v*", "HEAD")

version = os.environ.get("SM_VERSION")
if not version:
    if tag and not dirty:
        version = tag[1:]
    else:
        version = f"{base}-dev+{commit}" + (".dirty" if dirty else "")

board_id = env.GetProjectOption("custom_board_id", "unknown")  # noqa: F821

out_dir = os.path.join(project_dir, ".pio", "generated")
os.makedirs(out_dir, exist_ok=True)
header = os.path.join(out_dir, "build_info.h")
content = (
    "#pragma once\n"
    "// Generated by scripts/version.py - do not edit.\n"
    f'#define SM_VERSION "{version}"\n'
    f'#define SM_GIT_COMMIT "{commit}"\n'
    f'#define SM_BOARD_ID "{board_id}"\n'
)
try:
    with open(header) as f:
        unchanged = f.read() == content
except FileNotFoundError:
    unchanged = False
if not unchanged:
    with open(header, "w") as f:
        f.write(content)

env.Append(CPPPATH=[out_dir])  # noqa: F821
print(f"Starlink Monitor {version} ({board_id})")
