#pragma once

// Digit-only display fonts (Montserrat Medium, 4 bpp), generated by
// scripts/gen_fonts.sh. Glyphs: space % + - . / 0-9 : — nothing else.
// Use them only for numbers; anything else renders blank.
//
// Montserrat: Copyright 2011 The Montserrat Project Authors,
// SIL Open Font License 1.1 (https://openfontlicense.org). Taken from the
// copy bundled with LVGL (lvgl/scripts/built_in_font).

#include <lvgl.h>

LV_FONT_DECLARE(sm_font_num_48)
LV_FONT_DECLARE(sm_font_num_36)
